import Anthropic from "@anthropic-ai/sdk";
import type { Finding, Severity } from "../types.js";

const SYSTEM_PROMPT = `You are a security auditor specializing in code generated by AI tools (Cursor, Lovable, Bolt, Replit, Claude). Your audience is non-expert developers who may not understand security jargon.

Analyze the provided code for security vulnerabilities. Focus on issues that AI code generators commonly introduce:
- Missing authentication/authorization
- Exposed secrets or credentials
- SQL injection, XSS, and other injection flaws
- Insecure direct object references (IDOR)
- Missing input validation
- Insecure defaults (permissive CORS, no rate limiting)
- Client-side security checks without server-side enforcement
- Supabase RLS misconfigurations
- Unprotected payment/webhook endpoints

For each vulnerability found, respond with a JSON array of objects:
{
  "title": "Short, clear title",
  "severity": "critical|high|medium|low",
  "line": <approximate line number>,
  "description": "Plain-English explanation a non-developer can understand. What's the risk? What could an attacker do?",
  "fix": "Step-by-step fix instructions with code example if helpful",
  "category": "Secrets|Authentication|Authorization|Injection|Configuration|Payment Security|Data Exposure"
}

If no vulnerabilities are found, return an empty array: []

Rules:
- Only report real, exploitable issues — no theoretical concerns
- Be specific about what an attacker could do
- Explain fixes in beginner-friendly language
- Reference specific line numbers`;

export async function analyzeWithAI(
  files: { path: string; content: string }[],
  existingFindings: Finding[],
): Promise<Finding[]> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return [];

  const client = new Anthropic();

  // Build context: send files with existing findings for dedup
  const existingRules = new Set(
    existingFindings.map((f) => `${f.file}:${f.line}:${f.rule}`),
  );

  // Batch files into chunks to stay within token limits (~50KB per chunk)
  const chunks = chunkFiles(files, 50_000);
  const allFindings: Finding[] = [];

  for (const chunk of chunks) {
    const fileContext = chunk
      .map((f) => `--- ${f.path} ---\n${f.content}`)
      .join("\n\n");

    const existingNote = existingFindings.length > 0
      ? `\n\nThe following issues have already been found by static rules (do NOT duplicate these):\n${existingFindings.map((f) => `- ${f.file}:${f.line} — ${f.title}`).join("\n")}`
      : "";

    try {
      const response = await client.messages.create({
        model: "claude-sonnet-4-5-20250514",
        max_tokens: 4096,
        messages: [
          {
            role: "user",
            content: `Analyze these source files for security vulnerabilities:${existingNote}\n\n${fileContext}`,
          },
        ],
        system: SYSTEM_PROMPT,
      });

      const text = response.content
        .filter((block): block is Anthropic.TextBlock => block.type === "text")
        .map((block) => block.text)
        .join("");

      // Extract JSON from response (handles markdown code blocks)
      const jsonMatch = text.match(/\[[\s\S]*\]/);
      if (!jsonMatch) continue;

      const parsed = JSON.parse(jsonMatch[0]) as Array<{
        title: string;
        severity: Severity;
        line: number;
        description: string;
        fix: string;
        category: string;
      }>;

      for (const item of parsed) {
        // Find which file this finding belongs to
        const matchFile = chunk.find((f) => {
          const lines = f.content.split("\n");
          return item.line <= lines.length;
        });
        const file = matchFile?.path ?? chunk[0].path;

        const key = `${file}:${item.line}:AI`;
        if (existingRules.has(key)) continue;

        const content = chunk.find((f) => f.path === file)?.content ?? "";
        const lines = content.split("\n");
        const snippetStart = Math.max(0, item.line - 3);
        const snippetEnd = Math.min(lines.length, item.line + 2);
        const snippet = lines
          .slice(snippetStart, snippetEnd)
          .map((l, i) => {
            const num = snippetStart + i + 1;
            const marker = num === item.line ? ">" : " ";
            return `${marker} ${num.toString().padStart(4)} | ${l}`;
          })
          .join("\n");

        allFindings.push({
          id: `AI-${file}:${item.line}`,
          rule: "AI",
          severity: item.severity,
          title: item.title,
          description: item.description,
          file,
          line: item.line,
          snippet,
          fix: item.fix,
          category: item.category,
          source: "ai",
        });
      }
    } catch (error) {
      // AI analysis failed for this chunk — continue with others
      if (error instanceof Error && error.message.includes("API key")) {
        throw new Error(
          "Invalid ANTHROPIC_API_KEY. Get one at https://console.anthropic.com/",
        );
      }
    }
  }

  return allFindings;
}

function chunkFiles(
  files: { path: string; content: string }[],
  maxChars: number,
): { path: string; content: string }[][] {
  const chunks: { path: string; content: string }[][] = [];
  let current: { path: string; content: string }[] = [];
  let currentSize = 0;

  for (const file of files) {
    if (currentSize + file.content.length > maxChars && current.length > 0) {
      chunks.push(current);
      current = [];
      currentSize = 0;
    }
    current.push(file);
    currentSize += file.content.length;
  }

  if (current.length > 0) chunks.push(current);
  return chunks;
}
